// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_ALLOMON] = {
    .baseHP = 75,
    .baseAttack = 78,
    .baseDefense = 72,
    .baseSpeed = 98,
    .baseSpAttack = 67,
    .baseSpDefense = 72,
    .types = MON_TYPES(TYPE_DRAGON, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SPEED_BOOST, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Allomon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ALLOMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Allomon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterALLOMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterALLOMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterALLOMON, .shinyPalette = gMonPalette_RosterALLOMON,
    .iconSprite = gMonIcon_RosterALLOMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterALLOMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BAKEMON] = {
    .baseHP = 62,
    .baseAttack = 69,
    .baseDefense = 91,
    .baseSpeed = 72,
    .baseSpAttack = 77,
    .baseSpDefense = 70,
    .types = MON_TYPES(TYPE_GHOST, TYPE_DARK),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SHADOW_TAG, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Bakemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BAKEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Bakemon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBAKEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBAKEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBAKEMON, .shinyPalette = gMonPalette_RosterBAKEMON,
    .iconSprite = gMonIcon_RosterBAKEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBAKEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BALISTAMON] = {
    .baseHP = 74,
    .baseAttack = 94,
    .baseDefense = 78,
    .baseSpeed = 66,
    .baseSpAttack = 65,
    .baseSpDefense = 73,
    .types = MON_TYPES(TYPE_BUG, TYPE_STEEL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_BATTLE_ARMOR, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Balistamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BALISTAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Balistamon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBALISTAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBALISTAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBALISTAMON, .shinyPalette = gMonPalette_RosterBALISTAMON,
    .iconSprite = gMonIcon_RosterBALISTAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBALISTAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BALUCHIMON] = {
    .baseHP = 71,
    .baseAttack = 76,
    .baseDefense = 75,
    .baseSpeed = 89,
    .baseSpAttack = 76,
    .baseSpDefense = 78,
    .types = MON_TYPES(TYPE_PSYCHIC, TYPE_FAIRY),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_WHITE_SMOKE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Baluchimon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BALUCHIMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Baluchimon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBALUCHIMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBALUCHIMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBALUCHIMON, .shinyPalette = gMonPalette_RosterBALUCHIMON,
    .iconSprite = gMonIcon_RosterBALUCHIMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBALUCHIMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ANGELAMON] = {
    .baseHP = 56,
    .baseAttack = 60,
    .baseDefense = 46,
    .baseSpeed = 50,
    .baseSpAttack = 46,
    .baseSpDefense = 53,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_NORMAL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_OBLIVIOUS, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GRAY,
    .speciesName = _("Angelamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ANGELAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Angelamon, a Champion Digimon.\n"
                                  "Attribute: Free.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterANGELAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterANGELAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterANGELAMON, .shinyPalette = gMonPalette_RosterANGELAMON,
    .iconSprite = gMonIcon_RosterANGELAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterANGELAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ARESDRAMON] = {
    .baseHP = 76,
    .baseAttack = 91,
    .baseDefense = 76,
    .baseSpeed = 74,
    .baseSpAttack = 66,
    .baseSpDefense = 70,
    .types = MON_TYPES(TYPE_FIGHTING, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_BATTLE_ARMOR, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_PURPLE,
    .speciesName = _("Aresdramon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ARESDRAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Aresdramon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterARESDRAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterARESDRAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterARESDRAMON, .shinyPalette = gMonPalette_RosterARESDRAMON,
    .iconSprite = gMonIcon_RosterARESDRAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterARESDRAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ATAMADEMON] = {
    .baseHP = 77,
    .baseAttack = 90,
    .baseDefense = 75,
    .baseSpeed = 63,
    .baseSpAttack = 69,
    .baseSpDefense = 71,
    .types = MON_TYPES(TYPE_DRAGON, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_ROCK_HEAD, ABILITY_OBLIVIOUS, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Atamademon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ATAMADEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Atamademon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterATAMADEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterATAMADEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterATAMADEMON, .shinyPalette = gMonPalette_RosterATAMADEMON,
    .iconSprite = gMonIcon_RosterATAMADEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterATAMADEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ANGEMON] = {
    .baseHP = 65,
    .baseAttack = 73,
    .baseDefense = 70,
    .baseSpeed = 69,
    .baseSpAttack = 104,
    .baseSpDefense = 89,
    .types = MON_TYPES(TYPE_FAIRY, TYPE_FLYING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SYNCHRONIZE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Angemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ANGEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Angemon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterANGEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterANGEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterANGEMON, .shinyPalette = gMonPalette_RosterANGEMON,
    .iconSprite = gMonIcon_RosterANGEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterANGEMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ANKYLOMON] = {
    .baseHP = 73,
    .baseAttack = 81,
    .baseDefense = 95,
    .baseSpeed = 62,
    .baseSpAttack = 60,
    .baseSpDefense = 79,
    .types = MON_TYPES(TYPE_GROUND, TYPE_GROUND),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_ROUGH_SKIN, ABILITY_ROCK_HEAD, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Ankylomon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ANKYLOMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Ankylomon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterANKYLOMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterANKYLOMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterANKYLOMON, .shinyPalette = gMonPalette_RosterANKYLOMON,
    .iconSprite = gMonIcon_RosterANKYLOMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterANKYLOMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ARCHELOMON] = {
    .baseHP = 72,
    .baseAttack = 74,
    .baseDefense = 91,
    .baseSpeed = 62,
    .baseSpAttack = 66,
    .baseSpDefense = 74,
    .types = MON_TYPES(TYPE_WATER, TYPE_WATER),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_HYPER_CUTTER, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GREEN,
    .speciesName = _("Archelomon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ARCHELOMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Archelomon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterARCHELOMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterARCHELOMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterARCHELOMON, .shinyPalette = gMonPalette_RosterARCHELOMON,
    .iconSprite = gMonIcon_RosterARCHELOMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterARCHELOMONMoves,
    .teachableLearnset = sDigimonWaterTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
