// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_CHAMBLEMON] = {
    .baseHP = 74,
    .baseAttack = 71,
    .baseDefense = 73,
    .baseSpeed = 66,
    .baseSpAttack = 88,
    .baseSpDefense = 77,
    .types = MON_TYPES(TYPE_POISON, TYPE_POISON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_EFFECT_SPORE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Chamblemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_CHAMBLEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Chamblemon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterCHAMBLEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterCHAMBLEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterCHAMBLEMON, .shinyPalette = gMonPalette_RosterCHAMBLEMON,
    .iconSprite = gMonIcon_RosterCHAMBLEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterCHAMBLEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_CHAMELEMON] = {
    .baseHP = 62,
    .baseAttack = 72,
    .baseDefense = 74,
    .baseSpeed = 90,
    .baseSpAttack = 77,
    .baseSpDefense = 76,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_NORMAL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_COMPOUND_EYES, ABILITY_OBLIVIOUS, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GREEN,
    .speciesName = _("Chamelemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_CHAMELEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Chamelemon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterCHAMELEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterCHAMELEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterCHAMELEMON, .shinyPalette = gMonPalette_RosterCHAMELEMON,
    .iconSprite = gMonIcon_RosterCHAMELEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterCHAMELEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BIRDRAMON] = {
    .baseHP = 76,
    .baseAttack = 74,
    .baseDefense = 69,
    .baseSpeed = 92,
    .baseSpAttack = 78,
    .baseSpDefense = 71,
    .types = MON_TYPES(TYPE_FIRE, TYPE_FLYING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_FLASH_FIRE, ABILITY_MAGMA_ARMOR, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Birdramon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BIRDRAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Birdramon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBIRDRAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBIRDRAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBIRDRAMON, .shinyPalette = gMonPalette_RosterBIRDRAMON,
    .iconSprite = gMonIcon_RosterBIRDRAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBIRDRAMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DONSHOUMON] = {
    .baseHP = 78,
    .baseAttack = 80,
    .baseDefense = 75,
    .baseSpeed = 68,
    .baseSpAttack = 72,
    .baseSpDefense = 70,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_NORMAL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_OWN_TEMPO, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Donshoumon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DONSHOUMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Donshoumon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDONSHOUMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDONSHOUMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDONSHOUMON, .shinyPalette = gMonPalette_RosterDONSHOUMON,
    .iconSprite = gMonIcon_RosterDONSHOUMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDONSHOUMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DEXDORUMON] = {
    .baseHP = 74,
    .baseAttack = 93,
    .baseDefense = 71,
    .baseSpeed = 74,
    .baseSpAttack = 71,
    .baseSpDefense = 76,
    .types = MON_TYPES(TYPE_GHOST, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INTIMIDATE, ABILITY_IMMUNITY, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("DexDorugamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DEXDORUMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("DexDorugamon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDEXDORUMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDEXDORUMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDEXDORUMON, .shinyPalette = gMonPalette_RosterDEXDORUMON,
    .iconSprite = gMonIcon_RosterDEXDORUMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDEXDORUMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DIATRYMON] = {
    .baseHP = 73,
    .baseAttack = 77,
    .baseDefense = 75,
    .baseSpeed = 91,
    .baseSpAttack = 70,
    .baseSpDefense = 72,
    .types = MON_TYPES(TYPE_FLYING, TYPE_FLYING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SPEED_BOOST, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Diatrymon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DIATRYMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Diatrymon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDIATRYMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDIATRYMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDIATRYMON, .shinyPalette = gMonPalette_RosterDIATRYMON,
    .iconSprite = gMonIcon_RosterDIATRYMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDIATRYMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_CLOCKMON] = {
    .baseHP = 65,
    .baseAttack = 79,
    .baseDefense = 69,
    .baseSpeed = 80,
    .baseSpAttack = 92,
    .baseSpDefense = 65,
    .types = MON_TYPES(TYPE_ELECTRIC, TYPE_STEEL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_VOLT_ABSORB, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GRAY,
    .speciesName = _("Clockmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_CLOCKMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Clockmon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterCLOCKMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterCLOCKMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterCLOCKMON, .shinyPalette = gMonPalette_RosterCLOCKMON,
    .iconSprite = gMonIcon_RosterCLOCKMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterCLOCKMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DEPTHMON] = {
    .baseHP = 64,
    .baseAttack = 72,
    .baseDefense = 96,
    .baseSpeed = 80,
    .baseSpAttack = 69,
    .baseSpDefense = 84,
    .types = MON_TYPES(TYPE_WATER, TYPE_STEEL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SWIFT_SWIM, ABILITY_RAIN_DISH, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Depthmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DEPTHMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Depthmon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDEPTHMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDEPTHMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDEPTHMON, .shinyPalette = gMonPalette_RosterDEPTHMON,
    .iconSprite = gMonIcon_RosterDEPTHMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDEPTHMONMoves,
    .teachableLearnset = sDigimonWaterTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DEPUTYMON] = {
    .baseHP = 75,
    .baseAttack = 66,
    .baseDefense = 70,
    .baseSpeed = 72,
    .baseSpAttack = 100,
    .baseSpDefense = 73,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_STEEL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INTIMIDATE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BROWN,
    .speciesName = _("Deputymon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DEPUTYMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Deputymon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDEPUTYMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDEPUTYMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDEPUTYMON, .shinyPalette = gMonPalette_RosterDEPUTYMON,
    .iconSprite = gMonIcon_RosterDEPUTYMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDEPUTYMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FLYBEEMON] = {
    .baseHP = 64,
    .baseAttack = 75,
    .baseDefense = 77,
    .baseSpeed = 93,
    .baseSpAttack = 73,
    .baseSpDefense = 67,
    .types = MON_TYPES(TYPE_BUG, TYPE_STEEL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_HUSTLE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Flybeemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FLYBEEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Flybeemon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFLYBEEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFLYBEEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFLYBEEMON, .shinyPalette = gMonPalette_RosterFLYBEEMON,
    .iconSprite = gMonIcon_RosterFLYBEEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFLYBEEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
