// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_CHRYSALMON] = {
    .baseHP = 83,
    .baseAttack = 77,
    .baseDefense = 99,
    .baseSpeed = 52,
    .baseSpAttack = 66,
    .baseSpDefense = 85,
    .types = MON_TYPES(TYPE_DARK, TYPE_DARK),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SHELL_ARMOR, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_PURPLE,
    .speciesName = _("Chrysalmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_CHRYSALMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Chrysalmon, a Champion Digimon.\n"
                                  "Attribute: Uknown.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterCHRYSALMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterCHRYSALMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterCHRYSALMON, .shinyPalette = gMonPalette_RosterCHRYSALMON,
    .iconSprite = gMonIcon_RosterCHRYSALMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterCHRYSALMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_CITRAMON] = {
    .baseHP = 63,
    .baseAttack = 87,
    .baseDefense = 69,
    .baseSpeed = 75,
    .baseSpAttack = 100,
    .baseSpDefense = 69,
    .types = MON_TYPES(TYPE_FIGHTING, TYPE_GRASS),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_CHLOROPHYLL, ABILITY_NATURAL_CURE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Citramon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_CITRAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Citramon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterCITRAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterCITRAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterCITRAMON, .shinyPalette = gMonPalette_RosterCITRAMON,
    .iconSprite = gMonIcon_RosterCITRAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterCITRAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FANGMON] = {
    .baseHP = 77,
    .baseAttack = 75,
    .baseDefense = 70,
    .baseSpeed = 90,
    .baseSpAttack = 69,
    .baseSpDefense = 69,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_DARK),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INTIMIDATE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Fangmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FANGMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Fangmon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFANGMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFANGMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFANGMON, .shinyPalette = gMonPalette_RosterFANGMON,
    .iconSprite = gMonIcon_RosterFANGMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFANGMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FILMON] = {
    .baseHP = 73,
    .baseAttack = 88,
    .baseDefense = 73,
    .baseSpeed = 72,
    .baseSpAttack = 77,
    .baseSpDefense = 75,
    .types = MON_TYPES(TYPE_ELECTRIC, TYPE_ELECTRIC),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_ROUGH_SKIN, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GRAY,
    .speciesName = _("Filmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FILMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Filmon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFILMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFILMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFILMON, .shinyPalette = gMonPalette_RosterFILMON,
    .iconSprite = gMonIcon_RosterFILMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFILMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DARCMON] = {
    .baseHP = 83,
    .baseAttack = 93,
    .baseDefense = 72,
    .baseSpeed = 70,
    .baseSpAttack = 71,
    .baseSpDefense = 74,
    .types = MON_TYPES(TYPE_FAIRY, TYPE_FLYING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_GUTS, ABILITY_SYNCHRONIZE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Darcmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DARCMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Darcmon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDARCMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDARCMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDARCMON, .shinyPalette = gMonPalette_RosterDARCMON,
    .iconSprite = gMonIcon_RosterDARCMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDARCMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_EYESMON] = {
    .baseHP = 77,
    .baseAttack = 66,
    .baseDefense = 71,
    .baseSpeed = 90,
    .baseSpAttack = 69,
    .baseSpDefense = 67,
    .types = MON_TYPES(TYPE_DARK, TYPE_DARK),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_KEEN_EYE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLACK,
    .speciesName = _("Eyesmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_EYESMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Eyesmon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterEYESMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterEYESMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterEYESMON, .shinyPalette = gMonPalette_RosterEYESMON,
    .iconSprite = gMonIcon_RosterEYESMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterEYESMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DECKDRAMON] = {
    .baseHP = 66,
    .baseAttack = 71,
    .baseDefense = 76,
    .baseSpeed = 70,
    .baseSpAttack = 112,
    .baseSpDefense = 75,
    .types = MON_TYPES(TYPE_STEEL, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INTIMIDATE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BROWN,
    .speciesName = _("Deckdramon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DECKDRAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Deckdramon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDECKDRAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDECKDRAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDECKDRAMON, .shinyPalette = gMonPalette_RosterDECKDRAMON,
    .iconSprite = gMonIcon_RosterDECKDRAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDECKDRAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DELTAMON] = {
    .baseHP = 73,
    .baseAttack = 90,
    .baseDefense = 74,
    .baseSpeed = 70,
    .baseSpAttack = 77,
    .baseSpDefense = 75,
    .types = MON_TYPES(TYPE_DRAGON, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_HUGE_POWER, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Deltamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DELTAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Deltamon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDELTAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDELTAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDELTAMON, .shinyPalette = gMonPalette_RosterDELTAMON,
    .iconSprite = gMonIcon_RosterDELTAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDELTAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_COELAMON] = {
    .baseHP = 73,
    .baseAttack = 78,
    .baseDefense = 92,
    .baseSpeed = 72,
    .baseSpAttack = 73,
    .baseSpDefense = 80,
    .types = MON_TYPES(TYPE_WATER, TYPE_ROCK),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_STURDY, ABILITY_SWIFT_SWIM, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Coelamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_COELAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Coelamon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterCOELAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterCOELAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterCOELAMON, .shinyPalette = gMonPalette_RosterCOELAMON,
    .iconSprite = gMonIcon_RosterCOELAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterCOELAMONMoves,
    .teachableLearnset = sDigimonWaterTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BOOGIEMON] = {
    .baseHP = 73,
    .baseAttack = 70,
    .baseDefense = 77,
    .baseSpeed = 74,
    .baseSpAttack = 92,
    .baseSpDefense = 71,
    .types = MON_TYPES(TYPE_PSYCHIC, TYPE_DARK),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SHADOW_TAG, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Boogiemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BOOGIEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Boogiemon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBOOGIEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBOOGIEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBOOGIEMON, .shinyPalette = gMonPalette_RosterBOOGIEMON,
    .iconSprite = gMonIcon_RosterBOOGIEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBOOGIEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
