// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_BURAIMON] = {
    .baseHP = 68,
    .baseAttack = 83,
    .baseDefense = 70,
    .baseSpeed = 97,
    .baseSpAttack = 71,
    .baseSpDefense = 66,
    .types = MON_TYPES(TYPE_FLYING, TYPE_FIGHTING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INNER_FOCUS, ABILITY_STICKY_HOLD, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Buraimon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BURAIMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Buraimon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBURAIMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBURAIMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBURAIMON, .shinyPalette = gMonPalette_RosterBURAIMON,
    .iconSprite = gMonIcon_RosterBURAIMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBURAIMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ELEPHANMON] = {
    .baseHP = 77,
    .baseAttack = 74,
    .baseDefense = 75,
    .baseSpeed = 89,
    .baseSpAttack = 76,
    .baseSpDefense = 75,
    .types = MON_TYPES(TYPE_ELECTRIC, TYPE_STEEL),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_LEVITATE, ABILITY_HUGE_POWER, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Elephanmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ELEPHANMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Elephanmon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterELEPHANMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterELEPHANMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterELEPHANMON, .shinyPalette = gMonPalette_RosterELEPHANMON,
    .iconSprite = gMonIcon_RosterELEPHANMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterELEPHANMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BAOHUCKMON] = {
    .baseHP = 91,
    .baseAttack = 79,
    .baseDefense = 73,
    .baseSpeed = 75,
    .baseSpAttack = 73,
    .baseSpDefense = 70,
    .types = MON_TYPES(TYPE_FIGHTING, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INNER_FOCUS, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Baohuckmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BAOHUCKMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Baohuckmon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBAOHUCKMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBAOHUCKMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBAOHUCKMON, .shinyPalette = gMonPalette_RosterBAOHUCKMON,
    .iconSprite = gMonIcon_RosterBAOHUCKMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBAOHUCKMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BAROMON] = {
    .baseHP = 68,
    .baseAttack = 65,
    .baseDefense = 70,
    .baseSpeed = 63,
    .baseSpAttack = 84,
    .baseSpDefense = 72,
    .types = MON_TYPES(TYPE_PSYCHIC, TYPE_PSYCHIC),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SHADOW_TAG, ABILITY_SYNCHRONIZE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GREEN,
    .speciesName = _("Baromon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BAROMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Baromon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBAROMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBAROMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBAROMON, .shinyPalette = gMonPalette_RosterBAROMON,
    .iconSprite = gMonIcon_RosterBAROMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBAROMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FIRAMON] = {
    .baseHP = 74,
    .baseAttack = 75,
    .baseDefense = 71,
    .baseSpeed = 90,
    .baseSpAttack = 73,
    .baseSpDefense = 69,
    .types = MON_TYPES(TYPE_FIRE, TYPE_FLYING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_DROUGHT, ABILITY_BLAZE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Firamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FIRAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Firamon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFIRAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFIRAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFIRAMON, .shinyPalette = gMonPalette_RosterFIRAMON,
    .iconSprite = gMonIcon_RosterFIRAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFIRAMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FLADRAMON] = {
    .baseHP = 66,
    .baseAttack = 81,
    .baseDefense = 75,
    .baseSpeed = 80,
    .baseSpAttack = 93,
    .baseSpDefense = 77,
    .types = MON_TYPES(TYPE_FIRE, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_VITAL_SPIRIT, ABILITY_BLAZE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Flamedramon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FLADRAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Flamedramon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFLADRAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFLADRAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFLADRAMON, .shinyPalette = gMonPalette_RosterFLADRAMON,
    .iconSprite = gMonIcon_RosterFLADRAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFLADRAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FLAWIZAMON] = {
    .baseHP = 76,
    .baseAttack = 63,
    .baseDefense = 70,
    .baseSpeed = 77,
    .baseSpAttack = 98,
    .baseSpDefense = 82,
    .types = MON_TYPES(TYPE_FIRE, TYPE_PSYCHIC),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_BLAZE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Flawizamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FLAWIZAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Flawizamon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFLAWIZAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFLAWIZAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFLAWIZAMON, .shinyPalette = gMonPalette_RosterFLAWIZAMON,
    .iconSprite = gMonIcon_RosterFLAWIZAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFLAWIZAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_EXERMON] = {
    .baseHP = 77,
    .baseAttack = 75,
    .baseDefense = 70,
    .baseSpeed = 89,
    .baseSpAttack = 76,
    .baseSpDefense = 68,
    .types = MON_TYPES(TYPE_BUG, TYPE_ELECTRIC),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_LIMBER, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLACK,
    .speciesName = _("Exermon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_EXERMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Exermon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterEXERMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterEXERMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterEXERMON, .shinyPalette = gMonPalette_RosterEXERMON,
    .iconSprite = gMonIcon_RosterEXERMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterEXERMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DORUGAMON] = {
    .baseHP = 75,
    .baseAttack = 86,
    .baseDefense = 72,
    .baseSpeed = 74,
    .baseSpAttack = 69,
    .baseSpDefense = 71,
    .types = MON_TYPES(TYPE_DRAGON, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INTIMIDATE, ABILITY_LEVITATE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLACK,
    .speciesName = _("Dorugamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DORUGAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Dorugamon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDORUGAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDORUGAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDORUGAMON, .shinyPalette = gMonPalette_RosterDORUGAMON,
    .iconSprite = gMonIcon_RosterDORUGAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDORUGAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DORULUMON] = {
    .baseHP = 78,
    .baseAttack = 92,
    .baseDefense = 74,
    .baseSpeed = 75,
    .baseSpAttack = 68,
    .baseSpDefense = 70,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_GROUND),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SAND_VEIL, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Dorulumon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DORULUMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Dorulumon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDORULUMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDORULUMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDORULUMON, .shinyPalette = gMonPalette_RosterDORULUMON,
    .iconSprite = gMonIcon_RosterDORULUMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDORULUMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
