// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_DARKTYRMON] = {
    .baseHP = 76,
    .baseAttack = 93,
    .baseDefense = 73,
    .baseSpeed = 66,
    .baseSpAttack = 83,
    .baseSpDefense = 75,
    .types = MON_TYPES(TYPE_DARK, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INTIMIDATE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLACK,
    .speciesName = _("DarkTyranmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DARKTYRMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("DarkTyranmon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDARKTYRMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDARKTYRMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDARKTYRMON, .shinyPalette = gMonPalette_RosterDARKTYRMON,
    .iconSprite = gMonIcon_RosterDARKTYRMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDARKTYRMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FLARIZAMON] = {
    .baseHP = 99,
    .baseAttack = 72,
    .baseDefense = 70,
    .baseSpeed = 70,
    .baseSpAttack = 80,
    .baseSpDefense = 69,
    .types = MON_TYPES(TYPE_FIRE, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_FLASH_FIRE, ABILITY_MAGMA_ARMOR, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Flarizamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FLARIZAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Flarizamon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFLARIZAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFLARIZAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFLARIZAMON, .shinyPalette = gMonPalette_RosterFLARIZAMON,
    .iconSprite = gMonIcon_RosterFLARIZAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFLARIZAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DOLPHMON] = {
    .baseHP = 70,
    .baseAttack = 68,
    .baseDefense = 72,
    .baseSpeed = 96,
    .baseSpAttack = 82,
    .baseSpDefense = 80,
    .types = MON_TYPES(TYPE_WATER, TYPE_WATER),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_TORRENT, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Dolphmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DOLPHMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Dolphmon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDOLPHMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDOLPHMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDOLPHMON, .shinyPalette = gMonPalette_RosterDOLPHMON,
    .iconSprite = gMonIcon_RosterDOLPHMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDOLPHMONMoves,
    .teachableLearnset = sDigimonWaterTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_BULKMON] = {
    .baseHP = 95,
    .baseAttack = 82,
    .baseDefense = 77,
    .baseSpeed = 79,
    .baseSpAttack = 74,
    .baseSpDefense = 70,
    .types = MON_TYPES(TYPE_ELECTRIC, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_VITAL_SPIRIT, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Bulkmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BULKMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Bulkmon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBULKMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBULKMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBULKMON, .shinyPalette = gMonPalette_RosterBULKMON,
    .iconSprite = gMonIcon_RosterBULKMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBULKMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DIGMON] = {
    .baseHP = 95,
    .baseAttack = 79,
    .baseDefense = 74,
    .baseSpeed = 71,
    .baseSpAttack = 66,
    .baseSpDefense = 72,
    .types = MON_TYPES(TYPE_BUG, TYPE_GROUND),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SAND_STREAM, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Digmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DIGMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Digmon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDIGMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDIGMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDIGMON, .shinyPalette = gMonPalette_RosterDIGMON,
    .iconSprite = gMonIcon_RosterDIGMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDIGMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DINOHYUMON] = {
    .baseHP = 76,
    .baseAttack = 90,
    .baseDefense = 71,
    .baseSpeed = 72,
    .baseSpAttack = 68,
    .baseSpDefense = 71,
    .types = MON_TYPES(TYPE_FIGHTING, TYPE_DRAGON),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_GUTS, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GREEN,
    .speciesName = _("Dinohyumon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DINOHYUMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Dinohyumon, a Champion Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDINOHYUMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDINOHYUMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDINOHYUMON, .shinyPalette = gMonPalette_RosterDINOHYUMON,
    .iconSprite = gMonIcon_RosterDINOHYUMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDINOHYUMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_DOBERMON] = {
    .baseHP = 65,
    .baseAttack = 75,
    .baseDefense = 71,
    .baseSpeed = 93,
    .baseSpAttack = 80,
    .baseSpDefense = 68,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_DARK),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_PICKUP, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLACK,
    .speciesName = _("Dobermon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_DOBERMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Dobermon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterDOBERMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterDOBERMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterDOBERMON, .shinyPalette = gMonPalette_RosterDOBERMON,
    .iconSprite = gMonIcon_RosterDOBERMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterDOBERMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_APEMON] = {
    .baseHP = 69,
    .baseAttack = 86,
    .baseDefense = 72,
    .baseSpeed = 75,
    .baseSpAttack = 68,
    .baseSpDefense = 67,
    .types = MON_TYPES(TYPE_NORMAL, TYPE_FIGHTING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_LIMBER, ABILITY_TRACE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Apemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_APEMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Apemon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterAPEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterAPEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterAPEMON, .shinyPalette = gMonPalette_RosterAPEMON,
    .iconSprite = gMonIcon_RosterAPEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterAPEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_AQUILAMON] = {
    .baseHP = 68,
    .baseAttack = 76,
    .baseDefense = 66,
    .baseSpeed = 103,
    .baseSpAttack = 70,
    .baseSpDefense = 65,
    .types = MON_TYPES(TYPE_FLYING, TYPE_FLYING),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_RUN_AWAY, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Aquilamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_AQUILAMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Aquilamon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterAQUILAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterAQUILAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterAQUILAMON, .shinyPalette = gMonPalette_RosterAQUILAMON,
    .iconSprite = gMonIcon_RosterAQUILAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterAQUILAMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_FLYMON] = {
    .baseHP = 67,
    .baseAttack = 77,
    .baseDefense = 78,
    .baseSpeed = 88,
    .baseSpAttack = 70,
    .baseSpDefense = 66,
    .types = MON_TYPES(TYPE_FLYING, TYPE_BUG),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_POISON_POINT, ABILITY_SWARM, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Flymon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_FLYMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Flymon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterFLYMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterFLYMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterFLYMON, .shinyPalette = gMonPalette_RosterFLYMON,
    .iconSprite = gMonIcon_RosterFLYMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterFLYMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
