// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_GATOMON] = {
    .baseHP = 66,
    .baseAttack = 67,
    .baseDefense = 62,
    .baseSpeed = 89,
    .baseSpAttack = 65,
    .baseSpDefense = 68,
    .types = MON_TYPES(TYPE_FAIRY, TYPE_FAIRY),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_NATURAL_CURE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Gatomon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_GATOMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Gatomon, a Champion Digimon.\n"
                                  "Attribute: Vaccne.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterGATOMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterGATOMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterGATOMON, .shinyPalette = gMonPalette_RosterGATOMON,
    .iconSprite = gMonIcon_RosterGATOMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterGATOMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_GEREMON] = {
    .baseHP = 84,
    .baseAttack = 64,
    .baseDefense = 65,
    .baseSpeed = 62,
    .baseSpAttack = 73,
    .baseSpDefense = 60,
    .types = MON_TYPES(TYPE_BUG, TYPE_BUG),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_STENCH, ABILITY_LIQUID_OOZE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Geremon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_GEREMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Geremon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterGEREMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterGEREMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterGEREMON, .shinyPalette = gMonPalette_RosterGEREMON,
    .iconSprite = gMonIcon_RosterGEREMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterGEREMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_GESOMON] = {
    .baseHP = 73,
    .baseAttack = 90,
    .baseDefense = 74,
    .baseSpeed = 75,
    .baseSpAttack = 69,
    .baseSpDefense = 70,
    .types = MON_TYPES(TYPE_WATER, TYPE_WATER),
    .catchRate = 115, .expYield = 150,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_SLOW,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_SWIFT_SWIM, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Gesomon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_GESOMON, .categoryName = _("Champion"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Gesomon, a Champion Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterGESOMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterGESOMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterGESOMON, .shinyPalette = gMonPalette_RosterGESOMON,
    .iconSprite = gMonIcon_RosterGESOMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterGESOMONMoves,
    .teachableLearnset = sDigimonWaterTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
