// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_SILPHYMON] = {
    .baseHP = 80,
    .baseAttack = 90,
    .baseDefense = 75,
    .baseSpeed = 110,
    .baseSpAttack = 105,
    .baseSpDefense = 80,
    .types = MON_TYPES(TYPE_FLYING, TYPE_FAIRY),
    .catchRate = 45, .expYield = 210,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_KEEN_EYE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Silphymon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_SILPHYMON, .categoryName = _("Ultimate"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Silphymon, an Ultimate Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterSILPHYMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterSILPHYMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterSILPHYMON, .shinyPalette = gMonPalette_RosterSILPHYMON,
    .iconSprite = gMonIcon_RosterSILPHYMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterSILPHYMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_SHURIMON] = {
    .baseHP = 65,
    .baseAttack = 95,
    .baseDefense = 65,
    .baseSpeed = 115,
    .baseSpAttack = 70,
    .baseSpDefense = 65,
    .types = MON_TYPES(TYPE_GRASS, TYPE_WATER),
    .catchRate = 60, .expYield = 175,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_TECHNICIAN, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_GREEN,
    .speciesName = _("Shurimon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_SHURIMON, .categoryName = _("Armor"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Shurimon, an Armor Digimon.\n"
                                  "Attribute: Free.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterSHURIMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterSHURIMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterSHURIMON, .shinyPalette = gMonPalette_RosterSHURIMON,
    .iconSprite = gMonIcon_RosterSHURIMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterSHURIMONMoves,
    .teachableLearnset = sDigimonWaterTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_MAGNAMON] = {
    .baseHP = 80,
    .baseAttack = 100,
    .baseDefense = 105,
    .baseSpeed = 95,
    .baseSpAttack = 80,
    .baseSpDefense = 85,
    .types = MON_TYPES(TYPE_STEEL, TYPE_FAIRY),
    .catchRate = 60, .expYield = 175,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_FULL_METAL_BODY, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Magnamon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_MAGNAMON, .categoryName = _("Armor"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Magnamon, an Armor Digimon.\n"
                                  "Attribute: Free.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterMAGNAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterMAGNAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterMAGNAMON, .shinyPalette = gMonPalette_RosterMAGNAMON,
    .iconSprite = gMonIcon_RosterMAGNAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterMAGNAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_WARGREYMON] = {
    .baseHP = 90,
    .baseAttack = 135,
    .baseDefense = 100,
    .baseSpeed = 100,
    .baseSpAttack = 90,
    .baseSpDefense = 85,
    .types = MON_TYPES(TYPE_FIRE, TYPE_FIGHTING),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_INTIMIDATE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("WarGreymon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_WARGREYMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("WarGreymon, a Mega Digimon.\n"
                                  "Attribute: Vaccine.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterWARGREYMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterWARGREYMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterWARGREYMON, .shinyPalette = gMonPalette_RosterWARGREYMON,
    .iconSprite = gMonIcon_RosterWARGREYMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterWARGREYMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_METALGARURUMON] = {
    .baseHP = 85,
    .baseAttack = 100,
    .baseDefense = 90,
    .baseSpeed = 120,
    .baseSpAttack = 115,
    .baseSpDefense = 90,
    .types = MON_TYPES(TYPE_ICE, TYPE_STEEL),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_ICE_BODY, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("MtlGarurumon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_METALGARURUMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("MtlGarurumon, a Mega Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterMETALGARURUMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterMETALGARURUMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterMETALGARURUMON, .shinyPalette = gMonPalette_RosterMETALGARURUMON,
    .iconSprite = gMonIcon_RosterMETALGARURUMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterMETALGARURUMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_PHOENIXMON] = {
    .baseHP = 95,
    .baseAttack = 100,
    .baseDefense = 85,
    .baseSpeed = 110,
    .baseSpAttack = 115,
    .baseSpDefense = 95,
    .types = MON_TYPES(TYPE_FIRE, TYPE_FLYING),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_REGENERATOR, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("Phoenixmon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_PHOENIXMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Phoenixmon, a Mega Digimon.\n"
                                  "Attribute: Vaccine.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterPHOENIXMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterPHOENIXMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterPHOENIXMON, .shinyPalette = gMonPalette_RosterPHOENIXMON,
    .iconSprite = gMonIcon_RosterPHOENIXMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterPHOENIXMONMoves,
    .teachableLearnset = sDigimonFlyingTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_HERCULESKABUTERIMON] = {
    .baseHP = 100,
    .baseAttack = 125,
    .baseDefense = 120,
    .baseSpeed = 65,
    .baseSpAttack = 105,
    .baseSpDefense = 85,
    .types = MON_TYPES(TYPE_BUG, TYPE_ELECTRIC),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_LIGHTNING_ROD, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_YELLOW,
    .speciesName = _("HKabuterimon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_HERCULESKABUTERIMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("HKabuterimon, a Mega Digimon.\n"
                                  "Attribute: Vaccine.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterHERCULESKABUTERIMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterHERCULESKABUTERIMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterHERCULESKABUTERIMON, .shinyPalette = gMonPalette_RosterHERCULESKABUTERIMON,
    .iconSprite = gMonIcon_RosterHERCULESKABUTERIMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterHERCULESKABUTERIMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_ROSEMON] = {
    .baseHP = 85,
    .baseAttack = 80,
    .baseDefense = 85,
    .baseSpeed = 115,
    .baseSpAttack = 135,
    .baseSpDefense = 100,
    .types = MON_TYPES(TYPE_GRASS, TYPE_FAIRY),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_TRIAGE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_RED,
    .speciesName = _("Rosemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_ROSEMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Rosemon, a Mega Digimon.\n"
                                  "Attribute: Data.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterROSEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterROSEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterROSEMON, .shinyPalette = gMonPalette_RosterROSEMON,
    .iconSprite = gMonIcon_RosterROSEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterROSEMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_VIKEMON] = {
    .baseHP = 120,
    .baseAttack = 125,
    .baseDefense = 105,
    .baseSpeed = 60,
    .baseSpAttack = 85,
    .baseSpDefense = 105,
    .types = MON_TYPES(TYPE_WATER, TYPE_ICE),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_THICK_FAT, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_WHITE,
    .speciesName = _("Vikemon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_VIKEMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Vikemon, a Mega Digimon.\n"
                                  "Attribute: Free.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterVIKEMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterVIKEMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterVIKEMON, .shinyPalette = gMonPalette_RosterVIKEMON,
    .iconSprite = gMonIcon_RosterVIKEMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterVIKEMONMoves,
    .teachableLearnset = sDigimonWaterTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_SERAPHIMON] = {
    .baseHP = 95,
    .baseAttack = 105,
    .baseDefense = 100,
    .baseSpeed = 95,
    .baseSpAttack = 115,
    .baseSpDefense = 90,
    .types = MON_TYPES(TYPE_FAIRY, TYPE_STEEL),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_JUSTIFIED, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLUE,
    .speciesName = _("Seraphimon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_SERAPHIMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Seraphimon, a Mega Digimon.\n"
                                  "Attribute: Vaccine.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterSERAPHIMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterSERAPHIMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterSERAPHIMON, .shinyPalette = gMonPalette_RosterSERAPHIMON,
    .iconSprite = gMonIcon_RosterSERAPHIMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterSERAPHIMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
