// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.
[SPECIES_BLACKWARGREYMON] = {
    .baseHP = 90,
    .baseAttack = 135,
    .baseDefense = 100,
    .baseSpeed = 100,
    .baseSpAttack = 90,
    .baseSpDefense = 85,
    .types = MON_TYPES(TYPE_DARK, TYPE_FIGHTING),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_MOXIE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLACK,
    .speciesName = _("BWarGreymon"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_BLACKWARGREYMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("BWarGreymon, a Mega Digimon.\n"
                                  "Attribute: Virus.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterBLACKWARGREYMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterBLACKWARGREYMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterBLACKWARGREYMON, .shinyPalette = gMonPalette_RosterBLACKWARGREYMON,
    .iconSprite = gMonIcon_RosterBLACKWARGREYMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterBLACKWARGREYMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},

[SPECIES_IMPERIALDRAMON] = {
    .baseHP = 100,
    .baseAttack = 130,
    .baseDefense = 95,
    .baseSpeed = 95,
    .baseSpAttack = 100,
    .baseSpDefense = 80,
    .types = MON_TYPES(TYPE_DRAGON, TYPE_STEEL),
    .catchRate = 15, .expYield = 270,
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = GROWTH_MEDIUM_FAST,
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = { ABILITY_PRESSURE, ABILITY_NONE, ABILITY_NONE },
    .bodyColor = BODY_COLOR_BLACK,
    .speciesName = _("Imperialdrmn"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_IMPERIALDRAMON, .categoryName = _("Mega"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("Imperialdrmn, a Mega Digimon.\n"
                                  "Attribute: Free.\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_RosterIMPERIALDRAMON, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_RosterIMPERIALDRAMON, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_RosterIMPERIALDRAMON, .shinyPalette = gMonPalette_RosterIMPERIALDRAMON,
    .iconSprite = gMonIcon_RosterIMPERIALDRAMON, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRosterIMPERIALDRAMONMoves,
    .teachableLearnset = sDigimonLandTeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    
},
