FileIsland_PrimaryVillage_ElderHouse_MapScripts::
	.byte 0

FileIsland_PrimaryVillage_ElderHouse_EventScript_Elder::
	msgbox FileIsland_PrimaryVillage_ElderHouse_Text_Elder, MSGBOX_NPC
	end

FileIsland_PrimaryVillage_ElderHouse_Text_Elder:
	.string "JIJIMON: Ho ho… A new Tamer!\p"
	.string "Long ago, Kuwagamon guarded the\n"
	.string "Ancient Ruins in peace.\p"
	.string "Lately its data has gone wild, and\n"
	.string "thickets choke every forest path.\p"
	.string "If your partner grows strong enough\n"
	.string "to Digivolve, you may calm it.$"
