// Generated by tools/digimon_maps/npc_sprites.py
static const struct SpriteFrameImage sPicTable_DigimonJijimon[] = {
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 0),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 1),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 2),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 3),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 4),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 5),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 6),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 7),
    overworld_frame(gObjectEventPic_DigimonJijimon, 4, 4, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonJijimon = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_JIJIMON, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 512, .width = 32, .height = 32, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M, .inanimate = FALSE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32, .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Standard, .images = sPicTable_DigimonJijimon,
};

static const struct SpriteFrameImage sPicTable_DigimonLeomon[] = {
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 0),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 1),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 2),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 3),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 4),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 5),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 6),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 7),
    overworld_frame(gObjectEventPic_DigimonLeomon, 8, 8, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonLeomon = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_LEOMON, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 2048, .width = 64, .height = 64, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_S, .inanimate = FALSE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_64x64, .subspriteTables = sOamTables_64x64,
    .anims = sAnimTable_Standard, .images = sPicTable_DigimonLeomon,
};

static const struct SpriteFrameImage sPicTable_DigimonDigitamamon[] = {
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 0),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 1),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 2),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 3),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 4),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 5),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 6),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 7),
    overworld_frame(gObjectEventPic_DigimonDigitamamon, 4, 4, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonDigitamamon = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_DIGITAMAMON, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 512, .width = 32, .height = 32, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_M, .inanimate = FALSE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_32x32, .subspriteTables = sOamTables_32x32,
    .anims = sAnimTable_Standard, .images = sPicTable_DigimonDigitamamon,
};

static const struct SpriteFrameImage sPicTable_DigimonMonzaemon[] = {
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 0),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 1),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 2),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 3),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 4),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 5),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 6),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 7),
    overworld_frame(gObjectEventPic_DigimonMonzaemon, 8, 8, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonMonzaemon = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_MONZAEMON, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 2048, .width = 64, .height = 64, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_S, .inanimate = FALSE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_64x64, .subspriteTables = sOamTables_64x64,
    .anims = sAnimTable_Standard, .images = sPicTable_DigimonMonzaemon,
};

static const struct SpriteFrameImage sPicTable_DigimonAndromon[] = {
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 0),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 1),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 2),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 3),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 4),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 5),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 6),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 7),
    overworld_frame(gObjectEventPic_DigimonAndromon, 8, 8, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonAndromon = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_ANDROMON, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 2048, .width = 64, .height = 64, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_S, .inanimate = FALSE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_64x64, .subspriteTables = sOamTables_64x64,
    .anims = sAnimTable_Standard, .images = sPicTable_DigimonAndromon,
};

static const struct SpriteFrameImage sPicTable_DigimonKuwagamon[] = {
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 0),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 1),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 2),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 3),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 4),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 5),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 6),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 7),
    overworld_frame(gObjectEventPic_DigimonKuwagamon, 8, 8, 8),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonKuwagamon = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_KUWAGAMON, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 2048, .width = 64, .height = 64, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_S, .inanimate = FALSE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_64x64, .subspriteTables = sOamTables_64x64,
    .anims = sAnimTable_Standard, .images = sPicTable_DigimonKuwagamon,
};

static const struct SpriteFrameImage sPicTable_DigimonDigivice[] = {
    overworld_frame(gObjectEventPic_DigimonDigivice, 2, 2, 0),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonDigivice = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_DIGIVICE, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 128, .width = 16, .height = 16, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_S, .inanimate = TRUE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x16, .subspriteTables = sOamTables_16x16,
    .anims = sAnimTable_Inanimate, .images = sPicTable_DigimonDigivice,
};

static const struct SpriteFrameImage sPicTable_DigimonDataChip[] = {
    overworld_frame(gObjectEventPic_DigimonDataChip, 2, 2, 0),
};

const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DigimonDataChip = {
    .tileTag = TAG_NONE, .paletteTag = OBJ_EVENT_PAL_TAG_DIGIMON_DATA_CHIP, .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,
    .size = 128, .width = 16, .height = 16, .paletteSlot = PALSLOT_NPC_1,
    .shadowSize = SHADOW_SIZE_S, .inanimate = TRUE,
    .compressed = FALSE, .tracks = TRACKS_FOOT,
    .oam = &gObjectEventBaseOam_16x16, .subspriteTables = sOamTables_16x16,
    .anims = sAnimTable_Inanimate, .images = sPicTable_DigimonDataChip,
};
