// Generated by tools/digimon_maps/npc_sprites.py
    {gObjectEventPal_DigimonJijimon, OBJ_EVENT_PAL_TAG_DIGIMON_JIJIMON},
    {gObjectEventPal_DigimonLeomon, OBJ_EVENT_PAL_TAG_DIGIMON_LEOMON},
    {gObjectEventPal_DigimonDigitamamon, OBJ_EVENT_PAL_TAG_DIGIMON_DIGITAMAMON},
    {gObjectEventPal_DigimonMonzaemon, OBJ_EVENT_PAL_TAG_DIGIMON_MONZAEMON},
    {gObjectEventPal_DigimonAndromon, OBJ_EVENT_PAL_TAG_DIGIMON_ANDROMON},
    {gObjectEventPal_DigimonKuwagamon, OBJ_EVENT_PAL_TAG_DIGIMON_KUWAGAMON},
    {gObjectEventPal_DigimonDigivice, OBJ_EVENT_PAL_TAG_DIGIMON_DIGIVICE},
    {gObjectEventPal_DigimonDataChip, OBJ_EVENT_PAL_TAG_DIGIMON_DATA_CHIP},
