// Generated by tools/digimon_maps/npc_sprites.py
    [OBJ_EVENT_GFX_DIGIMON_JIJIMON] = &gObjectEventGraphicsInfo_DigimonJijimon,
    [OBJ_EVENT_GFX_DIGIMON_LEOMON] = &gObjectEventGraphicsInfo_DigimonLeomon,
    [OBJ_EVENT_GFX_DIGIMON_DIGITAMAMON] = &gObjectEventGraphicsInfo_DigimonDigitamamon,
    [OBJ_EVENT_GFX_DIGIMON_MONZAEMON] = &gObjectEventGraphicsInfo_DigimonMonzaemon,
    [OBJ_EVENT_GFX_DIGIMON_ANDROMON] = &gObjectEventGraphicsInfo_DigimonAndromon,
    [OBJ_EVENT_GFX_DIGIMON_KUWAGAMON] = &gObjectEventGraphicsInfo_DigimonKuwagamon,
    [OBJ_EVENT_GFX_DIGIMON_DIGIVICE] = &gObjectEventGraphicsInfo_DigimonDigivice,
    [OBJ_EVENT_GFX_DIGIMON_DATA_CHIP] = &gObjectEventGraphicsInfo_DigimonDataChip,
