#!/usr/bin/env python3
"""Generate explicit Digimon replacements for legacy trainers and scripted content."""
import hashlib
import json
import re

from catalog import ROOT, roster

TOKEN = re.compile(r"\bSPECIES_([A-Z0-9_]+)\b")
EARLY = {"POOCHYENA": "GAZIMON", "ZIGZAGOON": "LABRAMON", "WURMPLE": "KUNEMON",
         "LOTAD": "BETAMON", "RALTS": "TAPIRMON", "SEEDOT": "FLORAMON",
         "GEODUDE": "GOTSUMON", "MAGIKARP": "OTAMAMON", "GOLDEEN": "SWIMMON",
         "TREECKO": "ARURAUMON", "TORCHIC": "CANDLEMON", "MUDKIP": "BETAMON"}


def legacy_ids():
    text = (ROOT / "include/constants/species.h").read_text().split("SPECIES_CUSTOM_START")[0]
    result, value = {}, -1
    for key, assignment in re.findall(r"^\s*SPECIES_(\w+)\s*(?:=\s*([^,]+))?,", text, re.M):
        if assignment:
            value = result[assignment.strip().removeprefix("SPECIES_")] if "SPECIES_" in assignment else int(assignment, 0)
        else:
            value += 1
        result[key] = value
    return result


def legacy_data():
    result = {}
    for path in sorted((ROOT / "src/data/pokemon/species_info").glob("gen_*_families.h")):
        for key, block in re.findall(r"\[SPECIES_(\w+)\]\s*=\s*\{(.*?)(?=\n    \[SPECIES_|\Z)", path.read_text(), re.S):
            typing = re.search(r"\.types\s*=\s*MON_TYPES\(([^)]+)\)", block)
            stats = [int(n) for n in re.findall(r"\.base(?:HP|Attack|Defense|Speed|SpAttack|SpDefense)\s*=\s*(\d+)", block)[:6]]
            result[key] = {"types": re.findall(r"TYPE_\w+", typing[1]) if typing else [],
                           "bst": sum(stats) if len(stats) == 6 else 350}
    return result


def replacements():
    rows, legacy, ids = roster(), legacy_data(), legacy_ids()
    mapping = {}
    for key, value in ids.items():
        if not value:
            continue
        info = legacy.get(key, {"types": [], "bst": 350})
        choices = {}
        for stage in ("Rookie", "Champion"):
            pool = [row for row in rows if row["stage"] == stage]
            best = min(pool, key=lambda row: (
                -len(set(row["types"]) & set(info["types"])),
                abs(sum(row["stats"].values()) - info["bst"]),
                hashlib.sha256((key + row["key"]).encode()).digest()))
            choices[stage.lower()] = best["key"]
        if key in EARLY:
            choices["rookie"] = EARLY[key]
        choices["default"] = choices["champion"] if info["bst"] >= 420 else choices["rookie"]
        choices["id"] = value
        mapping[key] = choices
    return mapping


def replace_tokens(text, mapping):
    return TOKEN.sub(lambda m: "SPECIES_" + mapping[m[1]]["default"] if m[1] in mapping else m[0], text)


def trainer_parties(path, mapping):
    lines = path.read_text().splitlines(keepends=True)
    count = 0
    for index, line in enumerate(lines):
        # Trainerproc permits explicit SPECIES_* identifiers, including abbreviated donor names.
        if not line.startswith("Level:") or index == 0:
            continue
        header_index = index - 1
        while header_index > 0 and lines[header_index - 1].strip():
            header_index -= 1
        header = lines[header_index].strip()
        if not header or header.startswith(("===", "/*")) or ":" in header:
            continue
        match = re.match(r"(.*?)(?: @ (.*))?$", header)
        name, item = match.groups()
        name = re.sub(r"\s+\([MF]\)$", "", name)
        nickname = re.match(r".*\(([^)]+)\)$", name)
        name = nickname[1] if nickname else name
        key = name.upper().removeprefix("SPECIES_").replace("-", "_").replace(" ", "_").replace(".", "").replace("'", "")
        if key not in mapping:
            continue
        level = int(line.split(":", 1)[1])
        target = mapping[key]["rookie"] if level < 24 else mapping[key]["default"]
        lines[header_index] = "SPECIES_" + target + (" @ " + item if item else "") + "\n"
        count += 1
    if count:
        path.write_text("".join(lines))
    return count


def main():
    mapping = replacements()
    (ROOT / "tools/digimon_roster/legacy_replacements.json").write_text(json.dumps(mapping, indent=2) + "\n")
    # The engine keeps legacy IDs for tests and old saves; runtime producers use this table.
    # Aliases that share an ID must resolve identically; use the first canonical name.
    seen, entries = set(), []
    for row in mapping.values():
        if row["id"] in seen:
            continue
        seen.add(row["id"])
        entries.append(f"    [{row['id']}] = {{SPECIES_{row['default']}, SPECIES_{row['rookie']}}},")
    includes = []
    directory = ROOT / "src/data/digimon_legacy"
    directory.mkdir(exist_ok=True)
    for offset in range(0, len(entries), 400):
        name = f"{offset // 400:02}.h"
        (directory / name).write_text("// Generated by tools/digimon_roster/content.py\n" + "\n".join(entries[offset:offset + 400]) + "\n")
        includes.append(f'#include "digimon_legacy/{name}"')
    (ROOT / "src/data/digimon_legacy.h").write_text("\n".join(includes) + "\n")
    total = sum(trainer_parties(path, mapping) for path in (ROOT / "src/data").glob("*.party"))
    scripts = list((ROOT / "data/maps").glob("*/scripts.inc")) + list((ROOT / "data/scripts").glob("*.inc"))
    # Production facility populations are explicit data, not battle-engine special cases.
    scripts += list((ROOT / "src/data/battle_frontier").glob("*.h"))
    changed = 0
    for path in scripts:
        text = path.read_text()
        updated = replace_tokens(text, mapping)
        if updated != text:
            path.write_text(updated)
            changed += 1
    print(f"Replaced {total} trainer party members and species references in {changed} content files.")


if __name__ == "__main__":
    main()
