#!/usr/bin/env python3
"""Generate reviewable expansion data from the pinned, curated donor roster."""
import hashlib
import json
import re
import sys

from catalog import ROOT, UPSTREAM, REVISION, URL, roster
from curated import ART_ONLY, EXTRA_EVOLUTIONS, STARTER_CHAMPIONS, STARTER_GROWTH

sys.path.insert(0, str(ROOT / "tools"))
from prepare_rookie_sprites import fit, icon_palette
from prepare_digimon_sprite import load_rgba_source, to_indexed_4bpp
from PIL import Image

HEADER = "// Generated by tools/digimon_roster/generate.py; edit the catalog/importer.\n"


def write(relative, text):
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    if relative.endswith(".h") and len(text.splitlines()) > 500:
        raise ValueError(f"Split generated include: {relative}")
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def enum_block(filename, first, last, rows):
    """Flatten generated enum members: the script assembler cannot include inside enums."""
    path = ROOT / filename
    text = path.read_text()
    begin = text.index(first) + len(first)
    end = text.index(last, begin)
    updated = text[:begin] + "\n" + "\n".join("    " + row for row in rows) + "\n" + text[end:]
    if updated != text:
        path.write_text(updated)


def chunks(relative, entries, size):
    includes = []
    for offset in range(0, len(entries), size):
        filename = f"{offset // size:02d}.h"
        write(f"{relative}/{filename}", HEADER + "\n".join(entries[offset:offset + size]))
        includes.append(f'#include "{relative.split("/")[-1]}/{filename}"')
    return "\n".join(includes) + "\n"


DWDS_URL = "https://www.spriters-resource.com/ds_dsi/dgmnworldds/asset/{}/"


def portraits(row):
    directory = ROOT / "graphics/pokemon" / row["slug"]
    source = directory / "source_front.png"
    row["source_sha256"] = hashlib.sha256(source.read_bytes()).hexdigest()
    if "asset" in row:
        row["source_url"] = DWDS_URL.format(row["asset"])
    else:
        row["source_url"] = f"{URL}/graphics/pokemon/{row.get('donor_path') or row['slug'] + '/front.png'}"
    front = to_indexed_4bpp(fit(load_rgba_source(source), (64, 64), (62, 62)))
    front.save(directory / "front.png", bits=4, transparency=0)
    # User-approved front-as-back policy, not a fabricated rear view.
    front.save(directory / "back.png", bits=4, transparency=0)
    icon = to_indexed_4bpp(fit(load_rgba_source(source), (32, 32), (30, 30)), icon_palette())
    sheet = Image.new("P", (32, 64), 0)
    sheet.putpalette(icon.getpalette())
    sheet.paste(icon, (0, 0))
    sheet.paste(icon, (0, 32))
    sheet.save(directory / "icon.png", bits=4, transparency=0)


def learnsets(rows):
    source = (UPSTREAM / "learnsets.h").read_text()
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", source, flags=re.S)
    raw = dict(re.findall(r"static const u16 s(\w+)LevelUpLearnset\[\] = \{(.*?)\};", source, re.S))
    raw = {name.replace("_", "").upper(): body for name, body in raw.items()}
    valid_moves = set(re.findall(r"\bMOVE_\w+", (ROOT / "include/constants/moves.h").read_text()))
    # A handful of donor-exclusive techniques do not exist in the Emerald move table.
    # Keep the level timing, with the closest engine move, until custom techniques land.
    move_map = {
        "MOVE_CORONA_FLAME": "MOVE_FLAMETHROWER", "MOVE_HOLY_SHOOT": "MOVE_AURA_SPHERE",
        "MOVE_CELSTL_CROSS": "MOVE_SACRED_SWORD", "MOVE_PARACHARGE": "MOVE_SPARK",
        "MOVE_GAO_RUSH": "MOVE_DOUBLE_HIT", "MOVE_GRAND_CROSS": "MOVE_HYPER_BEAM",
        "MOVE_BLESSING": "MOVE_LIFE_DEW", "MOVE_HOLY_BEAM": "MOVE_METEOR_BEAM",
        "MOVE_PROPHECY": "MOVE_FUTURE_SIGHT", "MOVE_STUN_STINGER": "MOVE_POISON_JAB",
        "MOVE_BABY_FLAME": "MOVE_EMBER",
    }
    entries = []
    for row in rows:
        if "curated_moves" in row:
            moves = row.pop("curated_moves")
        else:
            moves = [(int(level), move) for level, move in re.findall(
                r"LEVEL_UP_MOVE\(\s*(\d+),\s*(MOVE_\w+)\)", raw[row["key"].replace("_", "")])]
        moves = [(level, move_map.get(move, move)) for level, move in moves]
        invalid = {move for _, move in moves} - valid_moves
        if invalid:
            raise ValueError(f"Unsupported moves for {row['key']}: {invalid}")
        if not moves:
            raise ValueError(f"No starting moves: {row['key']}")
        if not any(level == 1 for level, _ in moves):
            # Donor assumes later acquisition. Our wild Rookies start at level 2.
            moves.insert(0, (1, moves[0][1]))
        # Several donor support species have only status moves until level 14+.
        # Every newly obtained Digimon must be able to attack immediately.
        moves = [(level, move) for level, move in moves if move != "MOVE_TACKLE"]
        moves.append((1, "MOVE_TACKLE"))
        # Preserve donor levels/moves, but order them: the engine stops at the first future level.
        moves = sorted(dict.fromkeys(moves), key=lambda item: item[0])
        row["moves"] = moves
        entries.append(f"static const struct LevelUpMove sRoster{row['key']}Moves[] = {{\n"
                       + "".join(f"    LEVEL_UP_MOVE({level}, {move}),\n" for level, move in moves)
                       + "    LEVEL_UP_END\n};\n")
    write("src/data/pokemon/level_up_learnsets/digimon_roster.h",
          HEADER + chunks("src/data/pokemon/level_up_learnsets/digimon_roster", entries, 12))


def evolutions(rows):
    source = (UPSTREAM / "evolution.h").read_text()
    raw = dict(re.findall(r"\[SPECIES_(\w+)\]\s*=\s*(.*?)(?=\n\s*\[SPECIES_|\Z)", source, re.S))
    allowed = {row["key"] for row in rows}
    for row in rows:
        if "curated_evolutions" in row:
            choices = row.pop("curated_evolutions")
        else:
            choices = re.findall(r"\{EVO_LEVEL,\s*(\d+),\s*SPECIES_(\w+)\}", raw.get(row["key"], ""))
        # Item-conditioned entries come first: the engine takes the first match.
        choices = EXTRA_EVOLUTIONS.get(row["key"], []) + [list(choice) for choice in choices]
        # Non-starters cannot yield an event-exclusive starter through evolution.
        row["evolutions"] = [[int(choice[0])] + list(choice[1:]) for choice in choices if choice[1] in allowed]
    inherit_growth(rows)


def inherit_growth(rows):
    """The engine recalculates level from experience, so a line must share one growth rate."""
    by_key = {row["key"]: row for row in rows}
    parents = {}
    for row in rows:
        for choice in row["evolutions"]:
            parents.setdefault(choice[1], set()).add(row["key"])

    def resolve(key):
        if key in STARTER_CHAMPIONS:
            return STARTER_GROWTH
        rates = {resolve(parent) for parent in parents.get(key, ())}
        if len(rates) > 1:
            raise ValueError(f"Pre-evolutions of {key} disagree on growth rate: {rates}")
        return rates.pop() if rates else by_key[key]["growthRate"]

    for row in rows:
        row["growthRate"] = resolve(row["key"])


def field_guide(rows):
    """Write the attribute metadata used by the in-game Field Guide."""
    attributes = {
        "VACCNE": "Vaccine", "VACCINE": "Vaccine", "DATA": "Data", "VIRUS": "Virus",
        "FREE": "Free", "UKNOWN": "Unknown", "UNKNOWN": "Unknown",
    }
    names = {}
    entries = []
    for row in rows:
        attribute = attributes.get(row["attribute"].upper(), row["attribute"])
        symbol = "sDigimonGuide" + attribute
        names.setdefault(attribute, f'static const u8 {symbol}[] = _("{attribute}");')
        entries.append(f"    {{ SPECIES_{row['key']}, {symbol} }},")
    text = HEADER + "\n".join(names.values()) + "\n\n"
    text += "static const struct DigimonFieldGuideData sDigimonRosterFieldGuide[] = {\n"
    text += "\n".join(entries) + "\n};\n"
    write("src/data/digimon_roster_field_guide.h", text)


def attributes(rows):
    values = {"VACCNE": "DIGIMON_ATTRIBUTE_VACCINE", "VACCINE": "DIGIMON_ATTRIBUTE_VACCINE",
              "DATA": "DIGIMON_ATTRIBUTE_DATA", "VIRUS": "DIGIMON_ATTRIBUTE_VIRUS",
              "FREE": "DIGIMON_ATTRIBUTE_FREE", "UKNOWN": "DIGIMON_ATTRIBUTE_UNKNOWN",
              "UNKNOWN": "DIGIMON_ATTRIBUTE_UNKNOWN"}
    entries = [values[row["attribute"].upper()] for row in rows]
    text = HEADER + "static const u8 sDigimonRosterAttributes[DIGIMON_ROSTER_COUNT] = {\n"
    text += "\n".join(f"    {entry}," for entry in entries) + "\n};\n"
    write("src/data/digimon_roster_attributes.h", text)


def species(row, dex):
    key, slug = row["key"], row["slug"]
    symbol = "Roster" + key
    teachables = "Water" if "TYPE_WATER" in row["types"] else "Flying" if "TYPE_FLYING" in row["types"] else "Land"
    stats = "\n".join(f"    .{name} = {value}," for name, value in row["stats"].items())
    evo = ""
    if row["evolutions"]:
        evo = ".evolutions = EVOLUTION(" + ", ".join(
            f"{{EVO_LEVEL, {choice[0]}, SPECIES_{choice[1]}"
            + (f", CONDITIONS({{IF_HOLD_ITEM, {choice[2]}}})" if len(choice) > 2 else "") + "}"
            for choice in row["evolutions"]) + "),"
    article = "an" if row["stage"][0] in "AEIOU" else "a"
    return f'''[SPECIES_{key}] = {{
{stats}
    .types = MON_TYPES({", ".join(row["types"])}),
    .catchRate = {row["catchRate"]}, .expYield = {row["expYield"]},
    .evYield_HP = 1,
    .genderRatio = MON_GENDERLESS, .eggCycles = 20,
    .friendship = STANDARD_FRIENDSHIP, .growthRate = {row["growthRate"]},
    .eggGroups = MON_EGG_GROUPS(EGG_GROUP_NO_EGGS_DISCOVERED),
    .abilities = {{ {row["abilities"]}, ABILITY_NONE }},
    .bodyColor = {row["bodyColor"]},
    .speciesName = _("{row["name"]}"), .cryId = CRY_PORYGON,
    .natDexNum = NATIONAL_DEX_{key}, .categoryName = _("{row["stage"]}"),
    .height = 10, .weight = 200,
    .description = COMPOUND_STRING("{row["name"]}, {article} {row["stage"]} Digimon.\\n"
                                  "Attribute: {row["attribute"]}.\\n"
                                  "Recorded in the Digital Field Guide."),
    .pokemonScale = 256, .trainerScale = 256,
    .frontPic = gMonFrontPic_{symbol}, .frontPicSize = MON_COORDS_SIZE(64, 64),
    .frontAnimFrames = sAnims_SingleFramePlaceHolder, .frontAnimId = ANIM_V_JUMPS_SMALL,
    .backPic = gMonBackPic_{symbol}, .backPicSize = MON_COORDS_SIZE(64, 64),
    .backAnimId = BACK_ANIM_NONE,
    .palette = gMonPalette_{symbol}, .shinyPalette = gMonPalette_{symbol},
    .iconSprite = gMonIcon_{symbol}, .iconPalIndex = 0,
    SHADOW(0, 4, SHADOW_SIZE_M)
    FOOTPRINT(QuestionMark)
    .levelUpLearnset = sRoster{key}Moves,
    .teachableLearnset = sDigimon{teachables}TeachableLearnset, .eggMoveLearnset = sNoneEggMoveLearnset,
    {evo}
}},
'''


def main():
    rows = roster()
    learnsets(rows)
    evolutions(rows)
    graphics, info, constants = [], [], []
    for index, row in enumerate(rows, 1):
        row["types"] = ["TYPE_FAIRY" if value == "TYPE_LIGHT" else value for value in row["types"]]
        row["abilities"] = row["abilities"].replace("ABILITY_EPIPHANY", "ABILITY_SYNCHRONIZE")
        portraits(row)
        row["dex"] = index
        row["species_id"] = 1582 + index
        constants.append(f"SPECIES_{row['key']},")
        info.append(species(row, index))
        for ctype, prefix, filename, extension in (
            ("u32", "FrontPic", "front", ".4bpp.lz"),
            ("u32", "BackPic", "back", ".4bpp.lz"),
            ("u16", "Palette", "front", ".gbapal"),
            ("u8", "Icon", "icon", ".4bpp"),
        ):
            graphics.append(f'const {ctype} gMon{prefix}_Roster{row["key"]}[] = '
                            f'INCGFX_{ctype.upper()}("graphics/pokemon/{row["slug"]}/{filename}.png", "{extension}");')
    for row in ART_ONLY:
        portraits(dict(row))
    field_guide(rows)
    attributes(rows)
    # Reuse legacy dex slots, keeping all three saved dex flag arrays the same size.
    # NationalPokedexNumToSpecies resolves these slots to their canonical Digimon.
    dex = [f"NATIONAL_DEX_{rows[0]['key']} = 1,"]
    dex += [f"NATIONAL_DEX_{row['key']}," for row in rows[1:]]
    dex.append("NATIONAL_DEX_ROSTER_END = NATIONAL_DEX_" + rows[-1]["key"] + ",")
    enum_block("include/constants/species.h", "    SPECIES_SALAMON,", "    SPECIES_CUSTOM_END,", constants)
    enum_block("include/constants/pokedex.h", "    NATIONAL_DEX_SALAMON,", "};", dex)
    write("src/data/pokemon/species_info/digimon_roster.h",
          HEADER + chunks("src/data/pokemon/species_info/digimon_roster", info, 10))
    write("src/data/graphics/digimon_roster.h",
          HEADER + chunks("src/data/graphics/digimon_roster", graphics, 400))
    write("tools/digimon_roster/manifest.json", json.dumps({
        "repository": "Luna3Step/DigimonEmerald", "revision": REVISION, "species": rows,
    }, indent=2) + "\n")
    print(f"Generated {len(rows)} new Digimon ({len(rows) + 10} total).")


if __name__ == "__main__":
    main()
